server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${NATIVE_PATH}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"

encrypt:
  key: ${AES_KEY}