server:
  port: 8080

spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: product-service
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - Path=/api/products/**
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/api/users/**, /api/users
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
#                - Path=/api/orders/**, /api/cart/**
#            - id: eureka
#              uri: http://localhost:8761
#              predicates:
#                - Path=/**

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh,shutdown,prometheus,metrics,health,info,loggers"
  endpoint:
    shutdown:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7