server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7


# Circuit Breaker

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true # register the service with health endpoint using actuator
        slidingWindowSize: 10 # defines the no of calls CB track
        minimumNumberOfCalls: 5 # minimum number of calls required to check
        permittedNumberOfCallsInHalfOpenState: 3 # in half open state 3 are allowed
        waitDurationInOpenState: 10s # how long CB stays open before moving half open
        failureRateThreshold: 50 #percentage value of 50% fails it will reject
        automaticTransitionFromOpenToHalfOpenEnabled: true # 10 seconds it will automatically move to half open
        slidingWindowType: count_based # using count based and time based is also there

## Go to resilence4j  -> guides -> circuit breaker -> create and configure CB
