server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true