server:
  port: 8082

spring:
  application:
    name: user-service
  mongodb:
#    uri: mongodb+srv://
#    database: userdb
    host: ${MONGO_HOST} # This is the value I expect to be overridden
    port: ${MONGO_PORT}
    database: ${MONGO_DATABASE}

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh,shutdown,prometheus,metrics,health,info,loggers"
  endpoint:
    shutdown:
      enabled: true
  tracing:
    sampling:
      probability: 1.0 # --  for tracing sample size here it is 100%. In prod it should be less 0.25 or 0.10

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7